name: discord-bot-prod
services:
  python-bot:
    # Build the image from the Dockerfile in the current directory
    build: .

    # Meaningful name for easy identification in 'docker ps'
    container_name: kokoloko_bot

    # Restart policy: Automatically restart if the bot crashes or the server reboots
    restart: unless-stopped

    # Load environment variables (API Token)
    env_file:
      - .env

    # Volume mount to access local files (like kokoloko.log or pokemon_data.csv updates)
    volumes:
      - .:/app
